@startuml
top to bottom direction 
skinparam Shadowing false
skinparam wrapWidth 200
skinparam usecase {
	BackgroundColor #64B5F6
	BorderColor #64B5F6
	ArrowColor Gray
}
'!@Relation
(Customer) --> (Location)
(Cargo) --> (DeliverySpecification)
(CustomerShared) --> (Customer)
(DeliveryHistory) --> (HandlingEvent)
(DeliverySpecification) --> (LocationService)
(CarrierMovement) --> (LocationShared)
(DeliverySpecification) -->(LocationShared)
(Cargo) -->(Customer)
(HandlingEvent) .[#red].> (Cargo):circular
(HandlingEvent) --> (CarrierMovement)
(Cargo) --> (CustomerShared)
(Cargo) --> (DeliveryHistory)
(LocationShared) --> (Location)

@enduml